apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-avalanche-subnet-evm.fullname" . }}
  labels:
    {{- include "helm-avalanche-subnet-evm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- include "helm-avalanche-subnet-evm.selectorLabels" . | nindent 4 }}
